### basic settings

# site properties and page defaults
title: Van den Akker Lab @ Leiden University Medical Center
description: Computational Biology with applications in hematologic (pre-)malignancies and immuno-hematology
logo: images/logo.svg
header: images/background.jpg
footer: images/background.jpg
baseurl: ""

# site social media and other links
links:
  email: e.b.van_den_akker@lumc.nl
  google-scholar: Erik van den Akker
  github: your-lab
  twitter: erikvandenakker

### advanced settings

# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
